version: "3.7"

services:
  app_proxy:
    image: getumbrel/app-proxy
    restart: unless-stopped
    # Umbrel’s proxy will forward HTTPS → HTTP to your app
    environment:
      APP_HOST: xed-cockpit_web_1
      APP_PORT: 9090
      # optional: PROXY_AUTH_ADD: "false" to bypass Umbrel auth
      # optional: PROXY_AUTH_WHITELIST: "/api/*"

  web:
    # Use/build an image that runs cockpit-ws (multi-arch if you’re on Pi)
    image: fedora/cockpitws
    restart: on-failure
    stop_grace_period: 1m
    command: ["cockpit-ws","--no-tls","--port","9090","--address","0.0.0.0"]
    volumes:
      - ${APP_DATA_DIR}/config/cockpit.conf:/etc/cockpit/cockpit.conf:ro
    # NOTE: No port mapping needed when using app_proxy
