version: "3.7"

services:
  app_proxy:
    environment:
      # Point Umbrel's proxy at the Cockpit backend
      APP_HOST: xed-cockpit_web_1
      APP_PORT: 9090
      # Trust upstream proxy headers (X-Forwarded-*)
      PROXY_TRUST_UPSTREAM: "true"

  web:
    image: quay.io/cockpit/ws:latest
    restart: on-failure
    stop_grace_period: 1m
    # Tell cockpit-ws that TLS is terminated by the reverse proxy (Umbrel)
    # and serve plain HTTP on 9090.
    command: ["/usr/libexec/cockpit-ws", "--no-tls", "--for-tls-proxy", "--port", "9090", "--address", "0.0.0.0"]
    volumes:
      # Provide an optional config file (see below) at /etc/cockpit/cockpit.conf
      - ${APP_DATA_DIR}/config:/etc/cockpit
