version: "3.7"

services:
  app_proxy:
    environment:
      # MUST be "<app-id>_<web-service>_1"
      APP_HOST: xed-cockpit_web_1
      APP_PORT: 9090

  web:
    image: quay.io/cockpit/ws:latest
    restart: on-failure
    stop_grace_period: 1m
    # No published ports; Umbrel's app_proxy handles 9090
    environment:
      - COCKPIT_SSH_KNOWN_HOSTS_FILE=/etc/ssh/ssh_known_hosts
    volumes:
      - ${APP_DATA_DIR}/config:/etc/cockpit
      - ${APP_DATA_DIR}/ssh_known_hosts:/etc/ssh/ssh_known_hosts
