version: "3.7"

services:
  app_proxy:
    environment:
      # Use the canonical container DNS name per Umbrel docs:
      # <app-id>_<service-name>_1
      APP_HOST: xed-cockpit_web_1
      APP_PORT: 9090
      PROXY_TRUST_UPSTREAM: "true"   # pass through X-Forwarded-* from Umbrel

  web:
    image: quay.io/cockpit/ws:latest
    restart: on-failure
    stop_grace_period: 1m
    init: true
    # No published ports; Umbrel's app_proxy connects internally.
    # We self-write a minimal cockpit.conf at startup so no manual edits are required.
    command:
      - /bin/sh
      - -c
      - |
        set -eu
        mkdir -p /etc/cockpit
        cat > /etc/cockpit/cockpit.conf <<'EOF'
        [WebService]
        ProtocolHeader = X-Forwarded-Proto
        AllowUnencrypted = true
        EOF

        BIN="/usr/libexec/cockpit-ws"
        if [ ! -x "$BIN" ]; then
          if [ -x /usr/lib/cockpit/cockpit-ws ]; then
            BIN=/usr/lib/cockpit/cockpit-ws
          elif command -v cockpit-ws >/dev/null 2>&1; then
            BIN="$(command -v cockpit-ws)"
          else
            echo "cockpit-ws not found"; sleep 600; exit 1
          fi
        fi

        # Listen on all interfaces, HTTP only (Umbrel terminates TLS)
        exec "$BIN" --no-tls --for-tls-proxy --address 0.0.0.0 --port 9090
    expose:
      - "9090"
