version: "3.7"

services:
  app_proxy:
    environment:
      # Must be "<app-id>_<web-service>_1" per Umbrel's template
      APP_HOST: xed-cockpit_web_1
      APP_PORT: 9090

  web:
    image: quay.io/cockpit/ws:latest
    restart: on-failure
    stop_grace_period: 1m
    # No published ports; Umbrel's app_proxy connects internally.
    command:
      - /bin/sh
      - -c
      - |
        set -eu
        # Write a minimal config so Cockpit knows it's behind a TLS proxy
        mkdir -p /etc/cockpit
        cat > /etc/cockpit/cockpit.conf <<'EOF'
        [WebService]
        ProtocolHeader = X-Forwarded-Proto
        AllowUnencrypted = true
        EOF

        # Find cockpit-ws (Fedora path first, Debian-style fallback)
        BIN="/usr/libexec/cockpit-ws"
        [ -x "$BIN" ] || BIN="/usr/lib/cockpit/cockpit-ws"

        # Run plain HTTP for the proxy, but generate HTTPS-aware CSP/origins
        exec "$BIN" --no-tls --for-tls-proxy --address 0.0.0.0 --port 9090
