version: "3.7"

services:
  # Umbrel's built-in reverse proxy
  app_proxy:
    environment:
      APP_HOST: cockpit
      APP_PORT: 9090
      # Uncomment to make the app public without Umbrel login (not recommended):
      # PROXY_AUTH_ADD: "false"

  # Cockpit web service (no host install needed when connecting via SSH)
  cockpit:
    container_name: cockpit_ws
    image: quay.io/cockpit/ws:latest
    restart: unless-stopped
    # Store SSH keys / known_hosts so you can use key-based auth in Cockpit
    volumes:
      - ${APP_DATA_DIR}/keys:/keys:ro
      - ${APP_DATA_DIR}/ssh_known_hosts:/root/.ssh/known_hosts
    environment:
      # Point Cockpit at your private key (place it in ${APP_DATA_DIR}/keys)
      - COCKPIT_SSH_KEY_PATH=/keys/id_ed25519
    stop_grace_period: 1m
